### ISSUE TITLE
Quesion for blog posting

### ISSUE THREAD

**Issue by superbderrick** [rubenRP/rubenr.dev#8]
Hey Amigo, 

I have some questions for blog posting

As you know I am making my blog based on your blog project.

If I write new posting, Do I have to make a new md file with According to the set rules? like below

```
title: "2 horas con Magento 2: Primeras impresiones (Front-end edition)"
hero_title: 2 horas con Magento 2
hero_subtitle: Primeras impresiones (Front-end edition)
hero_image: 1*OddzhRy0jxiADpTDXecWVg.jpeg
thumbnail: 1*OddzhRy0jxiADpTDXecWVg.jpeg
published: true
date: "2015-12-27T15:17:00.000Z"
taxonomy:
  category:
    - Articles
  tag:
    - Magento

```

Sorry I am doing gastby and type script first timely, it woud be great if you give to me good tips..

Thanks mate :)
